# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(200, 150, 1200, 500))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader()       
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.searchline=QtWidgets.QLineEdit(self.centralwidget)
        self.searchline.setGeometry(QtCore.QRect(210,100,900,30))
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.userbutton=QtWidgets.QPushButton(self.centralwidget)
        self.userbutton.setGeometry(QtCore.QRect(1450, 600, 300, 50))
        self.userbutton.setObjectName("Открыть таблицу с пользователями")
        self.userbutton.setText("Открыть таблицу с пользователями")
        self.logbutton=QtWidgets.QPushButton(self.centralwidget)
        self.logbutton.setGeometry(QtCore.QRect(1450, 700, 300, 50))
        self.logbutton.setText("Показать логи")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuwidget=QtWidgets.QComboBox(self.centralwidget)
        self.menuwidget.setGeometry(QtCore.QRect(100,150,100,30))
        self.menuwidget.addItem("Characters")
        self.menuwidget.addItem("Planets")
        self.menuwidget.addItem("Species")
        self.labeltable=QtWidgets.QLabel(self.centralwidget)
        self.labeltable.setGeometry(QtCore.QRect(100, 120, 150, 30))
        self.labeltable.setText("Выберите таблицу")
        self.additemwidget=QtWidgets.QTableWidget(self.centralwidget)
        self.additemwidget.setGeometry(QtCore.QRect(200, 600, 1200, 100))
        self.additemwidget.setObjectName("additemwidget")
        self.additembutton=QtWidgets.QPushButton(self.centralwidget)
        self.additembutton.setGeometry(QtCore.QRect(700, 700, 150, 40))
        self.additembutton.setText("Добавить запись")
        # self.additemwidget.horizontalHeader()       
        # self.additemwidget.setColumnCount(0)
        # self.additemwidget.setRowCount(0)
        self.search=QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(1130, 100, 100, 30))
        self.search.setText("Найти")

        self.labelcolor=QtWidgets.QLabel(self.centralwidget)
        self.labelcolor.setGeometry(QtCore.QRect(1450,100,100,20))
        self.labelcolor.setText("Выберите цвет:")
        self.colorRed = QtWidgets.QCheckBox(self.centralwidget)
        self.colorRed.setGeometry(QtCore.QRect(1450, 120, 81, 20))
        self.colorRed.setText("Красный")


        self.colorBlue = QtWidgets.QCheckBox(self.centralwidget)
        self.colorBlue.setGeometry(QtCore.QRect(1450, 140, 81, 20))
        self.colorBlue.setText("Синий")


        self.colorGreen = QtWidgets.QCheckBox(self.centralwidget)
        self.colorGreen.setGeometry(QtCore.QRect(1450, 160, 81, 20))
        self.colorGreen.setText("Зеленый")


        self.colorWhite = QtWidgets.QCheckBox(self.centralwidget)
        self.colorWhite.setGeometry(QtCore.QRect(1450, 180, 81, 20))
        self.colorWhite.setText("Белый")

        self.colorLight = QtWidgets.QCheckBox(self.centralwidget)
        self.colorLight.setGeometry(QtCore.QRect(1450, 200, 81, 20))
        self.colorLight.setText("Светлый")

        self.colorYellow = QtWidgets.QCheckBox(self.centralwidget)
        self.colorYellow.setGeometry(QtCore.QRect(1450, 220, 81, 20))
        self.colorYellow.setText("Желтый")

        self.colorBrown = QtWidgets.QCheckBox(self.centralwidget)
        self.colorBrown.setGeometry(QtCore.QRect(1450, 240, 90, 20))
        self.colorBrown.setText("Коричневый")

        self.colorDark = QtWidgets.QCheckBox(self.centralwidget)
        self.colorDark.setGeometry(QtCore.QRect(1450, 260, 81, 20))
        self.colorDark.setText("Темный")

        self.colorOrange = QtWidgets.QCheckBox(self.centralwidget)
        self.colorOrange.setGeometry(QtCore.QRect(1450, 280, 90, 20))
        self.colorOrange.setText("Оранжевый")

        self.colorFair = QtWidgets.QCheckBox(self.centralwidget)
        self.colorFair.setGeometry(QtCore.QRect(1450, 300, 81, 20))
        self.colorFair.setText("Fair")

        self.labelgender=QtWidgets.QLabel(self.centralwidget)
        self.labelgender.setGeometry(QtCore.QRect(1600,100,100,20))
        self.labelgender.setText("Выберите пол:")

        self.genderMale = QtWidgets.QCheckBox(self.centralwidget)
        self.genderMale.setGeometry(QtCore.QRect(1600, 120, 81, 20))
        self.genderMale.setText("Мужской")

        self.genderFemale = QtWidgets.QCheckBox(self.centralwidget)
        self.genderFemale.setGeometry(QtCore.QRect(1600, 140, 81, 20))
        self.genderFemale.setText("Женский")

        self.labelheight=QtWidgets.QLabel(self.centralwidget)
        self.labelheight.setGeometry(QtCore.QRect(1550,320,100,20))
        self.labelheight.setText("Выберите рост:")

        self.labelmass=QtWidgets.QLabel(self.centralwidget)
        self.labelmass.setGeometry(QtCore.QRect(1550,420,100,20))
        self.labelmass.setText("Выберите массу:")

        self.labeldelete=QtWidgets.QLabel(self.centralwidget)
        self.labeldelete.setGeometry(QtCore.QRect(700, 750, 350, 40))
        self.labeldelete.setText("Введите id записи, которую хотите удалить")
        self.deleteusers=QtWidgets.QLineEdit(self.centralwidget)
        self.deleteusers.setGeometry(QtCore.QRect(700, 800, 50, 30))
        self.deletebutton=QtWidgets.QPushButton(self.centralwidget)
        self.deletebutton.setGeometry(QtCore.QRect(760, 800,60,30))
        self.deletebutton.setText("Удалить")

        self.updatetable=QtWidgets.QPushButton(self.centralwidget)
        self.updatetable.setGeometry(QtCore.QRect(100,250,100,30))
        self.updatetable.setText("Обновить")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Развернуть"))
